#!/usr/bin/env fish

# TODO:
# - [x] clear-env

set bwrap_args

function echodo
    echo ' $' $argv >&2
    $argv
end
function _check_is_env
    for v in $argv
        if ! set -q v
            echo "environment is unset: $v" >&2
            exit 1
        end
    end
end
function _check_is_dir
    for v in $argv
        set p (path resolve $v)
        if ! test -d "$p"
            echo "path does not exist: $v" >&2
            exit 1
        end
    end
end

function _check_file_exists
    for v in $argv
        set p (string split -- : $argv)[1]
        if ! test -e "$p"
            echo "path does not exist: $v" >&2
            exit 1
        end
    end
end

argparse -s                                               \
    e/env-pass=+'!_check_is_env "$_flag_value"'           \
    f/file-pass=+'!_check_file_exists "$_flag_value"'  \
    F/rw-file-pass=+'!_check_file_exists "$_flag_value"'     \
    w/workdir='!_check_is_dir "$_flag_value"'             \
    c/clear-env                                           \
    h/help                                                \
    -- $argv                                              \

# Print help
if set -q _flag_help
    echo "Usage:"
    echo "  -e, --env-pass       passthrough an environment variable"
    echo "  -f, --file-pass      passthrough files and directories to the sandbox as readonly (~/.config or ./bashrc:~/.bashrc)"
    echo "  -F, --rw-file-pass   same as --file-pass, but make the target files read-write"
    echo "  -w, --workdir        change working directory before executing"
    echo "  -c, --clear-env"
    echo "  -h, --help"
    exit
end


#
# Make bubblewrap arguments
#
begin
    # Bubblewrap
    set -a bwrap_args \
        --die-with-parent # the child process can't outlive bwrap

    # Clear environment variables
    if set -q _flag_clear_env
        # Needs to happen early
        set -a bwrap_args --clearenv
    end

    # Unix
    set -a bwrap_args                               \
        --dev /dev                                  \
        --dir /home/user                            \
        --dir /run/user/"$(id -u)"                  \
        --dir /tmp                                  \
        --dir /var                                  \
        --hostname computer                         \
        --proc /proc                                \
        --ro-bind /usr /usr                         \
        --bind /opt /opt                            \
        --symlink /tmp/bs var/tmp                   \
        --symlink usr/bin /bin                      \
        --symlink usr/lib /lib                      \
        --symlink usr/lib64 /lib64                  \
        --symlink usr/sbin /sbin                    \

    #
    # Make temporary files
    #
    set tmpdir (mktemp -d)

    # /etc/group
    set group_fd $tmpdir/group
    getent group  65534 | sed 's/nobody/user/; s/65534/'"$(id -g)/" > $group_fd
    set -a bwrap_args --ro-bind $group_fd /etc/group

    # /etc/passwd (all users)
    set passwd_fd $tmpdir/passwd
    getent passwd 65534 | sed 's/nobody/user/; s/65534/'"$(id -u)/" > $passwd_fd
    set -a bwrap_args --ro-bind $passwd_fd /etc/passwd

    # /etc/resolv.conf (dns)
    set resolv_fd $tmpdir/resolv.conf
    echo "nameserver 1.1.1.1" >$resolv_fd
    set -a bwrap_args --ro-bind $resolv_fd /etc/resolv.conf

    # Hosts file (localhost)
    set hosts_fd $tmpdir/hosts
    string join -- '' '# Standard host addresses'\n          \
         '127.0.0.1  localhost'\n                            \
         '::1        localhost ip6-localhost ip6-loopback'\n \
         'ff02::1    ip6-allnodes'\n                         \
         'ff02::2    ip6-allrouters'\n                       \
         '# This host address'\n                             \
         "127.0.1.1  computer" >$hosts_fd
    set -a bwrap_args --ro-bind $hosts_fd /etc/hosts

    ## Namespace
    set -a bwrap_args    \
        --unshare-all    \
        --unshare-user   \
        --unshare-ipc    \
        --unshare-pid    \
        --unshare-net    \
        --unshare-uts    \
        --unshare-cgroup \
        --disable-userns \

    ## Display
    set -a bwrap_args \
        --ro-bind /run/user/"$(id -u)"/"$WAYLAND_DISPLAY" /run/user/"$(id -u)"/"$WAYLAND_DISPLAY" \
        --ro-bind-try /run/user/"$(id -u)"/pipewire-0 /run/user/"$(id -u)"/pipewire-0 \
        --ro-bind-try /run/user/"$(id -u)"/pulse /run/user/"$(id -u)"/pulse

    ## Process working directory
    if set -q _flag_workdir
        set path (path resolve $_flag_workdir)
        set workdir (path basename $path)
        set -a bwrap_args --bind "$(path resolve $_flag_workdir)" /project/"$workdir"
    else
        set workdir (basename "$PWD")
        set -a bwrap_args --bind "$PWD" /project/"$workdir"
    end

    function process_file_pass_arg
        # $argv[1]     - the flag to pass to bind things (should be --bind or --ro-bind)
        # $argv[2..-1] - the dirs to passthrough
        set -l homereg "$(string escape --style=regex -- "$HOME")"
        set -l bind_flag $argv[1]
        for f in $argv[2..-1]
            if string match -rq -- ':' $f
                set f (string split --max 1 -- : $f)
                set f_inside (string replace -r -- "^~" "$HOME" $f[2])
                set f_inside (string replace -r -- "^$homereg" '/home/user' $f_inside)
                set -a -- bwrap_args $bind_flag "$f[1]" "$f_inside"
            else if test (count $f) = 1
                set f_inside (string replace -r -- "^$homereg" '/home/user' $f)
                set -a -- bwrap_args $bind_flag "$f" "$f_inside"
            end
        end
    end

    # Passthrough files
    if set -q _flag_rw_file_pass
        process_file_pass_arg --bind $_flag_rw_file_pass
    end
    if set -q _flag_file_pass
        process_file_pass_arg --ro-bind $_flag_file_pass
    end

    # Networking
    set -a bwrap_args --share-net

    # Environment
    set -a bwrap_args                                 \
        --setenv TERM "$TERM"                         \
        # --setenv XDG_RUNTIME_DIR "/run/user/$(id -u)" \

    # User
    set -a bwrap_args                            \
        --setenv HOME /home/user                 \
        --setenv USER user                       \
        --uid (id -u)                            \
        --gid (id -g)                            \

    # Always passthrough $TERM (idk why you wouldn't want this)
    set -a bwrap_args         \
        --setenv TERM "$TERM" \

    # Passthrough environment variables
    if set -q _flag_env_pass
        for a in $_flag_env_pass
            if set -q $a
                set -a bwrap_args --setenv $a $$a
            end
        end
    end

    # Setup current working directory
    set -a bwrap_args                 \
        --chdir /project/"$workdir"   \
        --dir /project/"$workdir"     \

end

#
# Run bubblewrap
#
bwrap $bwrap_args                     \
      /bin/sh -c 'exec "$@"' -- $argv

# cleanup
rm -r "$tmpdir"
