#!/usr/bin/env fish

set scriptname (status basename)

# if not in keepass2env shell, relaunch with keepass2env
if ! set -q KEEPASS2ENV_SHELL
   if ! command -v keepass2env &> /dev/null
      echo "$scriptname: could not find keepass2env"
      exit 1
   end
   exec keepass2env -- (status filename) $argv
end

if contains 0 (count $argv)
   set argv opencode
end

bs --clear-env                                      \
   --env-pass     TERM                              \
   --env-pass     EDITOR                            \
   --env-pass     AK_OPENCODE_ZEN                   \
   --file-pass    ~/.config/opencode/opencode.jsonc \
   --file-pass    ~/.config/nvim                    \
   --rw-file-pass ~/.local/state/opencode           \
   --rw-file-pass ~/.local/share/opencode           \
   -- $argv
