#!/usr/bin/env fish

set bsp_args_append (string unescape "$BSP_ARGS_APPEND")
set bsp_executable $BSP_EXECUTABLE

set scriptname (status basename)

# Default value for bsp_executable
if test -z "$bsp_executable"
   set bsp_executable gemini
end

# if not in keepass2env shell, relaunch with keepass2env
if ! set -q KEEPASS2ENV_SHELL_DEPTH
   if ! command -v keepass2env &> /dev/null
      echo "$scriptname: could not find keepass2env"
      exit 1
   end
   exec keepass2env -- (status filename) $argv
end

bs --clear-env                                      \
   --username     $USER                             \
   --hostname     $hostname                         \
   --env-pass     EDITOR                            \
   --env-pass     AK_OPENCODE_ZEN                   \
   --file-pass    ~/.config/nvim                    \
   --rw-file-pass ~/.gemini                         \
   $bsp_args_append                                  \
   -- $bsp_executable $argv

