#!/usr/bin/env fish

# if not in keepass2env shell, relaunch with keepass2env
set scriptname (status basename)
if ! set -q KEEPASS2ENV_SHELL_DEPTH
   if ! command -v keepass2env &> /dev/null
      echo "$scriptname: could not find keepass2env"
      exit 1
   end
   exec keepass2env -- (status filename) $argv
end

set bsp_args_append (string unescape $BSP_ARGS_APPEND)
set bsp_executable $BSP_EXECUTABLE

# Default value for bsp_executable
if test -z "$bsp_executable"
   set bsp_executable opencode
end

# Use real cwd when running in neovim
if set -q NVIM
   set -a bsp_args_append --workdir-name $PWD
end

exec bs --clear-env                                  \
   --username     $USER                              \
   --hostname     $hostname                          \
   --env-pass     EDITOR                             \
   --env-pass     AK_OPENCODE_ZEN                    \
   --file-pass    ~/.config/opencode/opencode.jsonc  \
   --file-pass    ~/.config/nvim                     \
   --rw-file-pass ~/.local/state/opencode            \
   --rw-file-pass ~/.local/share/opencode            \
   $bsp_args_append                                  \
   -- $bsp_executable $argv

